name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter Category=Unit
    - name: Push to Github Packages
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/LoR.Client/LoR.Client.csproj
        NUGET_SOURCE: https://nuget.pkg.github.com/danspark/lor-api-client/index.json
        NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
    - name: Push to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/LoR.Client/LoR.Client.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
